### PR TITLE
ES7 does not have type mapping

### PR DESCRIPTION
**Pull request by bloodbare**

### CODE REVIEW

**Review by vangheem — COMMENTED** [review]
Can we make it an app_settings configuration?

**Comment by bloodbare** [comment]
for manager.py as default settings its not a function so would not work. Can we move DEFAULT_SETTINGS to a function ?

**Comment by vangheem** [comment]
Yes, I'm fine with that. Can it be configured as well? So we can provide our own custom default settings function?

Could we also bump the version?

**Review by vangheem — APPROVED** [review]
Looks good!

**Pull request merged**
