### PR TITLE
 Replace aioelasticsearch with elasticsearchpy>=7.8

### LINKED ISSUE #78: Replace aioelasticsearch with elasticsearchpy>=7.8

### PR DESCRIPTION
**Pull request by masipcat**
Close https://github.com/plone/guillotina_elasticsearch/issues/78

### CODE REVIEW

**Review by vangheem — APPROVED** [review]

**Review by bloodbare — COMMENTED** [review]
I feel ok with it, @nilbacardit26 can you also review with some use cases ?

**Comment by nilbacardit26** [comment]
Yes, I'll review it and let you know

**Comment by masipcat** [comment]
> Yes, I'll review it and let you know

ok! FYI: In my case, this PR didn't require any changes to my code, everything worked as before. Probably it'll work as well for you

EDIT: ... as long you don't use ES6 :P

**Comment by nilbacardit26** [comment]
@bloodbare I ran all the use cases I have without any problem!

**Pull request merged**
